### PR TITLE
Add BE Staff to the CODEOWNERS file as they should have a say to their workflows

### PR DESCRIPTION
**Pull request by Aloutsis**
# Orfium GitHub Actions

## Checklist

- [ ] I have reviewed my code and checked that there are no unrelated changes in this pull request
- [ ] I have created a JIRA ticket describing the purpose of this pull request
- [ ] I have checked if the changes to the templates are breaking or have contacted the DevOps team for feedback
- [ ] I have updated the template with the Actionlint Format guidelines: [Actionlint](https://github.com/rhysd/actionlint#readme). Information on how to do that are provided on the CONTRIBUTING.md file under docs/ folder.

### CODE REVIEW

**Review by johnecon — APPROVED** [review]

**Comment by johnecon** [comment]
@Aloutsis Should we do the same for https://github.com/Orfium/github-actions ?

**Comment by Aloutsis** [comment]
That is up to your guys. I don't think we have any workflows of ours there. BUT, we should always have a CODEOWNERS file, especially in repositories that contain reusable actions with many internal stakeholders. So, imho opinion, yes, we absolutely should.

**Comment by johnecon** [comment]
@Aloutsis I suggest we follow the same approach (both teams are owners of the reusable github actions for both repos)

**Comment by Aloutsis** [comment]
Ok. Let's add both. I tried creating a PR on github-actions but it seems like backend-staff team does not have sufficient permissions in order to be codeowners for the github-actions repository. We need to add them and then I'll create the PR. Branch already exists -> https://github.com/Orfium/github-actions/tree/feat/add-codeowners

**Review by nVlast — APPROVED** [review]

**Review by mgiannos — APPROVED** [review]

**Pull request merged**
