### PR TITLE
Allow Custom Frontend Subdomain

### PR DESCRIPTION
**Pull request by nVlast**
DEVOPS-1159

### CODE REVIEW

**Review by Aloutsis — APPROVED** [review]
Looks good

**Comment by johnecon** [comment]
not sure why @Orfium/backend-staff team is involved in this PR
This PR is pretty old in any case, @Aloutsis lets either close it or seek approval from @panvourtsis

**Comment by Aloutsis** [comment]
@johnecon backend-staff is included because they are the listed as CODEOWNERS in this repository, so they are included by default in everrything. Not really anything we can do to be honest. As for the validity if this Pull Request, i think it's safe to say that it's not needed anymore, close to 1 year of its creation. If Panagiotis is ok with it, we can close it.

**Comment by panvourtsis** [comment]
please let's close it

**Comment by Aloutsis** [comment]
Your wishes are my commands

**Pull request closed without merging**
