### PR TITLE
feat(test-e2e.yml): Add build context and build target as input parameters

### PR DESCRIPTION
**Pull request by constantakopoulos**
# Orfium GitHub Actions

## Description

Added build context and build target input parameters in test-e2e.yml in case we want to override the context and the target for the build process.

## Checklist

- [ ] I have reviewed my code and checked that there are no unrelated changes in this pull request
- [ ] I have created a JIRA ticket describing the purpose of this pull request
- [ ] I have checked if the changes to the templates are breaking or have contacted the DevOps team for feedback
- [ ] I have updated the template with the Actionlint Format guidelines: [Actionlint](https://github.com/rhysd/actionlint#readme). Information on how to do that are provided on the CONTRIBUTING.md file under docs/ folder.

### CODE REVIEW

**Review by Aloutsis — APPROVED** [review]
Looks good

**Review by nVlast — DISMISSED** [review]
Looks good to me. Approved

**Review by Aloutsis — APPROVED** [review]
Looks good

**Comment by constantakopoulos** [comment]
Closed until further investigation on how to build two different docker images in the e2e-test.yml

**Pull request closed without merging**
